[package]
name = "ultrapc/protifliogame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Flipper = "reselim/flipper@2.0.0"
Roact = "roblox/roact@1.4.4"
Knit = "sleitnick/knit@1.7.0"

[server-dependencies]
Profilestore = "lm-loleris/profilestore@1.0.3"